//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esercizio_12
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Utenti
    {
        public int Id { get; set; }
        public string NomeUtente { get; set; }
        public string Password { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Reparto { get; set; }
        public int Livello { get; set; }
    }
}
